# Sanitizers.cmake
option(ENABLE_ASAN "Enable AddressSanitizer in Debug builds" ON)
option(ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer in Debug builds" ON)
option(ENABLE_TSAN "Enable ThreadSanitizer in Debug builds" OFF)
option(ENABLE_STDLIB_ASSERTIONS "Enable standard library assertions in Debug builds" ON)

function(enable_sanitizers target_name)
    if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_CONFIGURATION_TYPES)
        if (CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
            if (ENABLE_ASAN AND ENABLE_TSAN)
                message(FATAL_ERROR "ENABLE_ASAN and ENABLE_TSAN cannot both be enabled")
            endif()
            if (ENABLE_STDLIB_ASSERTIONS)
                target_compile_definitions(${target_name} PRIVATE _GLIBCXX_ASSERTIONS)
            endif()
            if (ENABLE_ASAN OR ENABLE_UBSAN OR ENABLE_TSAN)
                target_compile_options(${target_name} PRIVATE -fno-omit-frame-pointer)
            endif()
            if (ENABLE_ASAN)
                target_compile_options(${target_name} PRIVATE -fsanitize=address)
                target_link_options(${target_name} PRIVATE -fsanitize=address)
            endif()
            if (ENABLE_UBSAN)
                target_compile_options(${target_name} PRIVATE -fsanitize=undefined)
                target_link_options(${target_name} PRIVATE -fsanitize=undefined)
            endif()
            if (ENABLE_TSAN)
                target_compile_options(${target_name} PRIVATE -fsanitize=thread)
                target_link_options(${target_name} PRIVATE -fsanitize=thread)
            endif()
        endif()
    endif()
endfunction()
